export const nationalities = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Stati Uniti",
  "Andorra",
  "Angola",
  "Antigua e Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaigian",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Barbuda",
  "Botswana",
  "Bielorussia",
  "Belgio",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia",
  "Brasile",
  "Regno Unito",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Birmania",
  "Burundi",
  "Cambogia",
  "Camerun",
  "Canada",
  "Capo Verde",
  "Repubblica Centrafricana",
  "Ciad",
  "Cile",
  "Cina",
  "Colombia",
  "Comore",
  "Congo",
  "Costa Rica",
  "Croazia",
  "Cuba",
  "Cipro",
  "Repubblica Ceca",
  "Danimarca",
  "Gibuti",
  "Repubblica Dominicana",
  "Olanda",
  "Timor Est",
  "Ecuador",
  "Egitto",
  "Emirati Arabi Uniti",
  "Guinea Equatoriale",
  "Eritrea",
  "Estonia",
  "Etiopia",
  "Figi",
  "Filippine",
  "Finlandia",
  "Francia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Tedesco",
  "Ghana",
  "Grecia",
  "Grenada",
  "Guatemala",
  "Guinea-Bissau",
  "Guinea",
  "Guyana",
  "Haiti",
  "Erzegovina",
  "Honduras",
  "Ungheria",
  "Kiribati",
  "Islanda",
  "Indian",
  "Indonesia",
  "Iran",
  "Iraq",
  "Irlanda",
  "Israel",
  "Italia",
  "Costa d'Avorio",
  "Giamaica",
  "Giappone",
  "Giordania",
  "Kazakhstan",
  "Kenya",
  "Saint Kitts e Nevis",
  "Kuwait",
  "Kirghizstan",
  "Laos",
  "Lettonia",
  "Libano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Lussemburgo",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malesia",
  "Maldive",
  "Mali",
  "Malta",
  "Isole Marshall",
  "Mauritania",
  "Mauritius",
  "Messico",
  "Micronesia",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Marocco",
  "Lesotho",
  "Botswana",
  "Mozambico",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nuova Zelanda",
  "Nicaragua",
  "Nigeria",
  "Niger",
  "Corea del Nord",
  "Irlanda del Nord",
  "Norvegia",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nuova Guinea",
  "Paraguay",
  "Peru",
  "Polonia",
  "Portogallo",
  "Qatar",
  "Romania",
  "Russia",
  "Ruanda",
  "Saint Lucia",
  "El Salvador",
  "Samoa",
  "San Marino",
  "Sao Tomé e Principe",
  "Arabia Saudita",
  "Scozia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovacchia",
  "Slovenia",
  "Isole Salomone",
  "Somalia",
  "Sud Africa",
  "Corea del Sud",
  "Spagna",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Svezia",
  "Svizzera",
  "Siria",
  "Taiwan",
  "Tagikistan",
  "Tanzania",
  "Thailandia",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunisia",
  "Turchia",
  "Tuvalu",
  "Uganda",
  "Ucraina",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Galles",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
